name: board test action # 테스트 관리 시 스크립트에 붙는 이름, 어떻게 작성되어도 무방

on:
  workflow_dispatch:  # 사용자가 실행했을 때
  pull_request:
    types: [opened, synchronize, reopened] # [풀리퀘생성시, 풀리퀘상황에서새로운코드푸시될때, 추가생성시]
# 워크 플로우 권한
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout # 단위 명령어의 이름
        uses: actions/checkout@v3.0.2 # 버전이 달라질 수 있음
      # JDK 세팅
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      # Secret 값 부여
      - name: secrets test
        run : echo secrets value = ${{ secrets.TEST_VALUE }}
      # OS에 실행권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # 그래들 테스트 코드 실행
      - name : Build with Gradle
        run: ./gradlew build -Pjasypt.encryptor.password=${{secrets.JASYPT_KEY_VALUE}} --parallel
