spring:
  application:
    name: gateway-server
  profiles:
    active: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter  # 추후에 사용할 전역 필터 틀
          args:
            message: Global Filter Default Message Test
            pre: true
            post: true
      routes: # 개별 마이크로서비스 정보를 routes에 기입함
        - id: board-service
          uri: http://3.34.146.225:8080/
          predicates:
            - Path=/board-service/**
          filters:
            - JwtTokenFilter
        - id: pass-service
          uri: http://3.38.117.113:8080/
          predicates:
            - Path=/pass-service/**
        - id: member-service
          uri: http://43.202.44.107:8080/
          predicates:
            - Path=/member-service/**
          filters:
            - JwtTokenFilter
        - id: product-service
          uri: http://3.34.192.232:8080/
          predicates:
            - Path=/product-service/**
          filters:
            - JwtTokenFilter
        - id: auction-service
          uri: http://13.125.245.67:8080/
          predicates:
            - Path=/auction-service/**
          filters:
            - JwtTokenFilter
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment-service/**
          filters:
            - JwtTokenFilter
          