spring:
  profiles:
    active: private
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}

  main:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: com.farmted.passservice.config.CustomCamelCaseToSnakeAndLowerCaseStrategy
    show-sql: true
    hibernate:
      ddl-auto: create

  #Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 5986

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 103819284407-g161ugj2ams4u5aosrgqvaq6lqlnimg2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
  mvc:
    view:
      prefix: /resources/static/**
      suffix: .html
server:
  port: 5986
