server:
  port: 8080
spring:
  application:
    name: board-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.farmted.boardservice.config.CustomCamelCaseToSnakeAndLowerCaseStrategy
    show-sql: true
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
## Discovery Client 세팅
eureka:
  client:
    register-with-eureka: true  # 유레카 서버에 등록
    fetch-registry: true  # 유레카 서버에서 서버 상태 지속적 감시 허락
    service-url:
      defaultZone: http://192.168.67.1:8761/eureka # 유레카 서버의 주소
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
## 스케줄러 세팅
schedules:
  cron: "* * * * * *"  # 1초마다 스케줄러 실행

